"""monitor：把三张镜像事实表转换为 TimescaleDB hypertable，并保留全局唯一身份。

按接收时刻 ``received_at`` 分区。hypertable 的唯一约束必须包含分区列，因此全局 ``event_id``
与 decision/health 的 ``stream_sequence`` 唯一由 monitor owner 内窄的普通身份表承载：身份表
保留 PK(event_id)、UNIQUE(stream_sequence)，并暴露覆盖 ``(event_id, received_at,
stream_sequence)`` 的唯一约束；事实表用复合主键 ``(event_id, received_at)`` 和指向该唯一约束
的复合外键，使同一事件无法跨分区重复、事实行的流序号无法偏离全局身份，真实 SQL 写错序号也
会被拒绝。只调用 ``create_hypertable`` 转换既有表，不创建任何压缩策略（原生压缩归 S021）；
中心迁移只作用于 ``nvsop``，不进入 ``training`` database。
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "0045"
down_revision: str | None = "0044"

# 迁移用原生 SQL 完成数据回填、hypertable 转换与降级还原；声明其触及的表，供迁移所有权门禁核对。
RAW_SQL_TABLES = frozenset(
    {
        "monitor_reported_decision",
        "monitor_reported_health",
        "monitor_observation",
        "monitor_decision_identity",
        "monitor_health_identity",
        "monitor_observation_identity",
    }
)

# fact -> (identity, 是否有流序号, 0044 原有的普通索引列)。窄的三表清单，不做通用框架。
_FACTS: dict[str, tuple[str, bool, tuple[str, ...]]] = {
    "monitor_reported_decision": (
        "monitor_decision_identity",
        True,
        ("host_id", "station_id", "backend_id", "received_at"),
    ),
    "monitor_reported_health": (
        "monitor_health_identity",
        True,
        ("host_id", "station_id", "received_at", "stream_id"),
    ),
    "monitor_observation": (
        "monitor_observation_identity",
        False,
        ("host_id", "station_id", "instance_id", "received_at"),
    ),
}


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    for fact, (identity, sequenced, _) in _FACTS.items():
        _create_identity(identity, sequenced=sequenced)
        _backfill_identity(fact, identity, sequenced=sequenced)
        _convert_fact(fact, identity, sequenced=sequenced)


def _create_identity(identity: str, *, sequenced: bool) -> None:
    columns = [
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
    ]
    key_columns = ["event_id", "received_at"]
    if sequenced:
        columns.append(
            sa.Column("stream_sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False)
        )
        key_columns.append("stream_sequence")
    op.create_table(
        identity,
        *columns,
        sa.PrimaryKeyConstraint("event_id", name=f"pk_{identity}"),
        sa.UniqueConstraint(*key_columns, name=f"uq_{identity}_fact_identity"),
    )
    if sequenced:
        op.create_unique_constraint(f"uq_{identity}_stream_sequence", identity, ["stream_sequence"])


def _backfill_identity(fact: str, identity: str, *, sequenced: bool) -> None:
    columns = "event_id, received_at, stream_sequence" if sequenced else "event_id, received_at"
    op.execute(f"INSERT INTO {identity} ({columns}) SELECT {columns} FROM {fact}")
    if sequenced:
        # 空表 setval(1,false) 让首个新序号为 1；已有值 setval(max,true) 从 max+1 继续。
        op.execute(
            f"SELECT setval(pg_get_serial_sequence('{identity}', 'stream_sequence'), "
            f"COALESCE((SELECT max(stream_sequence) FROM {identity}), 1), "
            f"(SELECT count(*) > 0 FROM {identity}))"
        )


def _convert_fact(fact: str, identity: str, *, sequenced: bool) -> None:
    if sequenced:
        op.drop_constraint(f"uq_{fact}_stream_sequence", fact, type_="unique")
        op.execute(f"ALTER TABLE {fact} ALTER COLUMN stream_sequence DROP IDENTITY")
    op.drop_constraint(f"pk_{fact}", fact, type_="primary")
    op.create_primary_key(f"pk_{fact}", fact, ["event_id", "received_at"])
    columns = ["event_id", "received_at"] + (["stream_sequence"] if sequenced else [])
    op.create_foreign_key(
        f"fk_{fact}_identity", fact, identity, columns, columns, ondelete="CASCADE"
    )
    if sequenced:
        # 原唯一约束提供了序号索引；hypertable 不能保留该唯一约束，改建非唯一索引。
        op.create_index(f"ix_{fact}_stream_sequence", fact, ["stream_sequence"])
    op.execute(f"SELECT create_hypertable('{fact}', 'received_at', migrate_data => true)")


def downgrade() -> None:
    # 不卸载 timescaledb：镜像把扩展预装在 template1，卸载会破坏同库其它对象；这里只把三张
    # hypertable 还原成 0044 的普通表。
    for fact, (identity, sequenced, indexes) in _FACTS.items():
        _restore_fact(fact, identity, sequenced=sequenced, indexes=indexes)


def _restore_fact(fact: str, identity: str, *, sequenced: bool, indexes: tuple[str, ...]) -> None:
    old = f"{fact}_downgrade"
    # LIKE 只取列形状，绝不 INCLUDING INDEXES：否则会复制 hypertable 的复合主键。
    op.execute(f"CREATE TABLE {old} (LIKE {fact} INCLUDING DEFAULTS)")
    if sequenced:
        op.execute(
            f"ALTER TABLE {old} ALTER COLUMN stream_sequence ADD GENERATED BY DEFAULT AS IDENTITY"
        )
    # 复合外键已保证事实行的 stream_sequence 等于身份表的全局序号，直接整行复制。
    op.execute(f"INSERT INTO {old} SELECT * FROM {fact}")
    if sequenced:
        op.execute(
            f"SELECT setval(pg_get_serial_sequence('{old}', 'stream_sequence'), "
            f"COALESCE((SELECT max(stream_sequence) FROM {old}), 1), "
            f"(SELECT count(*) > 0 FROM {old}))"
        )
    op.drop_table(fact)
    op.rename_table(old, fact)
    op.create_primary_key(f"pk_{fact}", fact, ["event_id"])
    if sequenced:
        op.create_unique_constraint(f"uq_{fact}_stream_sequence", fact, ["stream_sequence"])
    op.drop_table(identity)
    for column in indexes:
        op.create_index(f"ix_{fact}_{column}", fact, [column])
